### ISSUE TITLE
How to use global localization service

### ISSUE THREAD

**Issue by ArthurYu96** [at-wat/mcl_3dl#231] opened 2019-06-11 08:22 UTC
Thank you for your great works.
I run the demo and it works well, but I don't know how can I use the global localization service, should I write a client for the service?
Btw, if I want to use a real robot without IMU, what should I change?
Hope for your help, thanks

**Comment by at-wat** [comment] 2019-06-14 06:35
Global localization can be triggered by a ROS service.
You can use command line tools `rosservice call /global_localization`.

> Btw, if I want to use a real robot without IMU, what should I change?

This topic is duplicate of #223.
I have not yet decided how to support no-IMU system.

**Comment by at-wat** [comment] 2019-10-24 06:29
An example command to run global localization in the demonstration has been added to README. (https://github.com/at-wat/mcl_3dl/pull/238)

Feel free to reopen if you have question on this topic.

**Closed by at-wat** 2019-10-24 06:29 UTC
